# Generated by Django 5.1.7 on 2025-03-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carteira", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transacao",
            old_name="criado_em",
            new_name="realizado_em",
        ),
    ]
